name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '*' # Executa para qualquer tag
    branches:
      - feature/ajuste-da-pipeline # Executa quando a branch feature/ajuste-da-pipeline for atualizada

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Configurar variável de ambiente para o caminho base
      - name: Set BASE_PATH for GitHub Pages
        run: echo "NEXT_PUBLIC_BASE_PATH=/todo-app-react" >> .env

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Fazer o build
      - name: Build project
        run: npm run build

      # Deploy para gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./out
